-- Run this in Supabase SQL Editor.
-- IMPORTANT: Create the first Owner account in Supabase Authentication > Users.
-- Then replace OWNER_AUTH_USER_UUID below with that user's UUID and run the policy block.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  username text unique not null,
  role text not null default 'STAFF' check (role in ('OWNER','STAFF')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.templates (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.generated_designs (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users(id) on delete set null,
  customer_name text,
  model text,
  delivery_date text,
  photo_urls jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.templates enable row level security;
alter table public.generated_designs enable row level security;

-- Helper: current user's role.
create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.profiles p
  where p.id = auth.uid() and p.role = 'OWNER' and p.active = true
); $$;

-- Profiles: users can see their own profile; Owner can manage all profiles.
create policy "profile self read" on public.profiles
for select using (id = auth.uid() or public.is_owner());

create policy "owner manage profiles" on public.profiles
for all using (public.is_owner()) with check (public.is_owner());

-- Templates: signed-in active users can read; only Owner can write.
create policy "active users read templates" on public.templates
for select using (auth.uid() is not null);

create policy "owner manage templates" on public.templates
for all using (public.is_owner()) with check (public.is_owner());

-- Generated designs: users can insert/read their own; Owner can read all.
create policy "users insert designs" on public.generated_designs
for insert with check (created_by = auth.uid());

create policy "users read own designs" on public.generated_designs
for select using (created_by = auth.uid() or public.is_owner());

-- Storage bucket for photos/templates.
insert into storage.buckets (id, name, public)
values ('delivery-assets', 'delivery-assets', false)
on conflict (id) do nothing;

create policy "signed users upload assets"
on storage.objects for insert to authenticated
with check (bucket_id = 'delivery-assets');

create policy "signed users read assets"
on storage.objects for select to authenticated
using (bucket_id = 'delivery-assets');

-- First owner profile example:
-- insert into public.profiles (id,name,username,role,active)
-- values ('OWNER_AUTH_USER_UUID','Owner','owner','OWNER',true);
